import "./globals.css";
import {Nunito} from "next/font/google";
import React from "react";
import Providers from "@/app/components/DarkMode/Providers";
import Navbar from "@/app/components/navbar/Navbar";
import Footer from "@/app/components/footer/Footer";

const nunito = Nunito({subsets: ["latin"]});

export const metadata = {
    title: "Craft Hire",
    description: "Generated by create next app",
};

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className={nunito.className}>
        <Providers>
            {/*clients only*/}
            <Navbar/>
            {/*clients only*/}
            <div className="min-h-screen flex flex-col">
                <div className="flex-grow overflow-auto">
                    {children}
                </div>

                <div className="mt-auto">
                    <Footer/>
                </div>
            </div>
        </Providers>
        </body>
        </html>
    );
}
